[package]
name = "p24"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dashmap = "5.0.0"
fnv = "1.0.7"
hashbrown = "0.11.2"
rayon = "1.5.1"

[[bin]]
name = "other"
path = "bin/main.rs"
